#!/usr/bin/env bash
#
# =============================================================================
# BOOTSTRAP LOCAL / CI DEVELOPMENT MATERIAL
# =============================================================================
# Generates the throwaway cryptographic material and plaintext secure-property
# files that the application needs in order to *start*, so that `mvn test` and
# Anypoint Studio both work on a fresh clone.
#
# Why this exists
# ---------------
# global-config.xml builds a TLS context at application start, and the secure
# properties module resolves its file at the same moment. Neither is lazy. So
# an application that references keystores cannot boot — and therefore cannot
# run a single MUnit test — until those files exist on the classpath.
#
# Everything produced here is gitignored (*.jks, *.secure.yaml) and worthless:
# self-signed certificates valid for one year and passwords that are literally
# "changeit". That is deliberate. Real material for dev/test/prod is issued by
# the platform team and injected by the pipeline; nothing generated by this
# script should ever reach an environment.
#
# Usage:
#   ./scripts/bootstrap-local-dev.sh
#   mvn clean test -Dmule.env=local -Dmule.secure.key=localdevkey12345
# =============================================================================

set -euo pipefail

RES="src/main/resources"
KEYSTORE_DIR="${RES}/keystores"
TRUSTSTORE_DIR="${RES}/truststores"
PROPS_DIR="${RES}/properties"

STORE_PASS="changeit"
KEY_PASS="changeit"
DNAME="CN=localhost, OU=Integration, O=Utility Integration Platform, L=Milan, C=IT"

mkdir -p "${KEYSTORE_DIR}" "${TRUSTSTORE_DIR}" "${PROPS_DIR}"

# -----------------------------------------------------------------------------
# 1. Server keystore — used by the inbound HTTPS listener.
# -----------------------------------------------------------------------------
if [[ ! -f "${KEYSTORE_DIR}/local-keystore.jks" ]]; then
  echo "==> Generating local-keystore.jks"
  keytool -genkeypair \
    -alias local \
    -keyalg RSA -keysize 2048 -validity 365 \
    -dname "${DNAME}" \
    -keystore "${KEYSTORE_DIR}/local-keystore.jks" \
    -storetype JKS \
    -storepass "${STORE_PASS}" -keypass "${KEY_PASS}" \
    -ext "SAN=dns:localhost,ip:127.0.0.1"

  # The SII client certificate lives in the same store under its own alias,
  # mirroring production: mutual TLS to Acquirente Unico authenticates the
  # Seller with a distinct key pair from the one serving inbound traffic.
  echo "==> Adding seller-client-cert alias (SII mTLS)"
  keytool -genkeypair \
    -alias seller-client-cert \
    -keyalg RSA -keysize 2048 -validity 365 \
    -dname "CN=seller-client, OU=SII, O=Utility Integration Platform, C=IT" \
    -keystore "${KEYSTORE_DIR}/local-keystore.jks" \
    -storetype JKS \
    -storepass "${STORE_PASS}" -keypass "${KEY_PASS}"
else
  echo "==> local-keystore.jks already present, skipping"
fi

# -----------------------------------------------------------------------------
# 2. Truststore — the CA chain we accept from downstream systems. Locally it
#    just trusts our own self-signed certificate.
# -----------------------------------------------------------------------------
if [[ ! -f "${TRUSTSTORE_DIR}/local-truststore.jks" ]]; then
  echo "==> Generating local-truststore.jks"
  keytool -exportcert \
    -alias local \
    -keystore "${KEYSTORE_DIR}/local-keystore.jks" \
    -storepass "${STORE_PASS}" \
    -rfc -file /tmp/uip-local-cert.pem

  keytool -importcert -noprompt \
    -alias local \
    -file /tmp/uip-local-cert.pem \
    -keystore "${TRUSTSTORE_DIR}/local-truststore.jks" \
    -storetype JKS \
    -storepass "${STORE_PASS}"

  rm -f /tmp/uip-local-cert.pem
else
  echo "==> local-truststore.jks already present, skipping"
fi

# -----------------------------------------------------------------------------
# 3. Secure properties file.
#
#    Values are written in PLAINTEXT, not ![ciphertext]. The secure properties
#    module only attempts decryption on values wrapped in ![...] and passes
#    anything else through untouched, so a plaintext local file resolves
#    correctly with any key. That keeps the local loop free of a key-management
#    step while leaving the production mechanism (encrypted values + injected
#    key) exactly as it is.
# -----------------------------------------------------------------------------
if [[ ! -f "${PROPS_DIR}/local.secure.yaml" ]]; then
  echo "==> Writing local.secure.yaml (plaintext, gitignored, throwaway)"
  cat > "${PROPS_DIR}/local.secure.yaml" <<EOF
# GENERATED BY scripts/bootstrap-local-dev.sh — DO NOT COMMIT.
# Plaintext throwaway values for local runs and MUnit only.
sii:
  client_secret: "local-dev-not-a-real-secret"

salesforce:
  client_secret: "local-dev-not-a-real-secret"

billing:
  client_secret: "local-dev-not-a-real-secret"

oauth:
  client_secret: "local-dev-not-a-real-secret"

mq:
  client_secret: "local-dev-not-a-real-secret"

tls:
  keystore:
    password: "${STORE_PASS}"
    keyPassword: "${KEY_PASS}"
  truststore:
    password: "${STORE_PASS}"
EOF
else
  echo "==> local.secure.yaml already present, skipping"
fi

echo
echo "Done. Now run:"
echo "  mvn clean test -Dmule.env=local -Dmule.secure.key=localdevkey12345"
